const IconName = {
  Add: 'Add',
  Close: 'Close',
  Eye: 'Eye',
  Account: 'Account',
  Calendar: 'Calendar',
  Dashboard: 'Dashboard',
  Services: 'Services',
  Account_Focused: 'Account_Focused',
  Calendar_Focused: 'Calendar_Focused',
  Dashboard_Focused: 'Dashboard_Focused',
  Services_Focused: 'Services_Focused',
  Meetings: 'Meetings',
  Appointments: 'Appointments',
  Video_Conferences: 'Video_Conferences',
  Tasks: 'Tasks',
  Subjects: 'Subjects',
  Delegation: 'Delegation',
  Statistics: 'Statistics',
  Arrow_Right: 'Arrow_Right',
  Meetings_Dashboard: 'Meetings_Dashboard',
  Add_White: 'Add_White',
  Dots: 'Dots',
  Arrow_Left: 'Arrow_Left',
  Download: 'Download',
  Plus: 'Plus',
  Minus: 'Minus',
  Search: 'Search',
  Arrow_Down: 'Arrow_Down',
  Send: 'Send',
  Edit: 'Edit',
  Delete: 'Delete',
  Eye_Primary: 'Eye_Primary',
  Speaker: 'Speaker',
  Download_Primary: 'Download_Primary',
  CopyText: 'CopyText'
};

export default IconName;
